
<!DOCTYPE html>
<html lang="en">
<head>
<base href="<?= BASE_URL ?>">
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
<link rel="stylesheet" href="css/style.css">
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand" href="home">PelisPedia</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="home">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="categorias">Categorias</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="login">Log in</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="logout">Log Out</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="agregar">Agregar pelicula</a>
        </li>

      </ul>
    </div>
  </div>
</nav>
</head>

</html>