<?php require_once 'layouts/header.phtml' ?>

<h1 class="text-center mb-4">Editor de categorias</h1>
<div class=" row justify-content-center align-items-center">
    <form action="add/categoria" method="POST" class="text-center col-5">
        <div class="mb-3">
            <label class="form-label">Nueva categoria</label>
            <input required name="genre" type="text" class="form-control text-center border-dark" placeholder="nombre de la nueva categoria">
            <button type="submit" class="btn btn-outline-info mt-2 mb-2">Agregar</button>
        </div>
    </form>
</div>
<div class="row justify-content-center">
    <?php foreach ($genres as $genre): ?>
        <form action="editar/categoria/<?= $genre->id ?>" method="POST" class="row justify-content-center my-4 col-lg-6">
            <div class="col-12">
                <div class="form-group align-items-center">
                    <input required name="genre" type="text" class="form-control text-center border-dark" value="<?= $genre->genre ?>">
                    <div class="justify-content-center align-items-center">
                        <button type="submit" class="btn btn-outline-warning mt-2 mb-2">Editar</button>
                        <a href="eliminar/categoria/<?= $genre->id ?>" class="btn btn-outline-danger">Eliminar</a>
                    </div>
                </div>
            </div>
        </form>
    <?php endforeach ?>
</div>

<?php require_once 'layouts/footer.phtml' ?>