
<?php require_once 'layouts/header.phtml' ?>

<div class="row justify-content-center">
<form action="update/<?= $movie->id ?>" method="POST" class="row justify-content-center my-4 col-lg-6">
    <div class="row">
        <div class="col-9">
            <div class="form-group">
                <label>Título</label>
                <input required name="title" type="text" class="form-control" value="<?= $movie->title ?>">
            </div>
        </div>
        <div class="col-9">
            <div class="form-group">
                <label>Director</label>
                <input required name="director" type="text" class="form-control" value="<?= $movie->director ?>">
            </div>
        </div>

        <div class="col-3">
            <div class="form-group">
                <label>Genero</label>
                <select required name="genre" class="form-control">
                    <?php foreach ($genres as $genre) : ?>
                        <option value="<?= $genre->id ?>"> <?= $genre->genre ?></option>
                    <?php endforeach ?>
                </select>
            </div>
        </div>
        <div class="col-9">
            <div class="form-group">
                <label>Portada</label>
                <input required name="img" type="text" class="form-control" value="<?= $movie->img ?>"> 
            </div>
        </div>
    </div>

    <div class="form-group">
        <label>Descripcion</label>
        <textarea name="descrip" class="form-control" rows="3" value="<?= $movie->descrip ?>"></textarea>
    </div>

    <button type="submit" class="btn btn-primary mt-2 mb-2">Guardar</button>
</form>
</div>

<?php require_once 'layouts/footer.phtml' ?>