<?php require_once 'layouts/header.phtml' ?>

<form action="agregar" method="POST" class="my-4">
    <div class="row">
        <div class="col-9">
            <div class="form-group">
                <label>Título</label>
                <input required name="title" type="text" class="form-control">
            </div>
        </div>
        <div class="col-9">
            <div class="form-group">
                <label>Director</label>
                <input required name="director" type="text" class="form-control">
            </div>
        </div>

        <div class="col-3">
            <div class="form-group">
                <label>Genero</label>
                <?php foreach ($genres as $genre): ?>
                    <select required name="genre" class="form-control">
                        <option value="<?= $genre->id ?>"> <?= $genre->genre ?></option>
                    </select>
                <?php endforeach ?>
            </div>
        </div>
    </div>

    <div class="form-group">
        <label>Descripcion</label>
        <textarea name="description" class="form-control" rows="3"></textarea>
    </div>

    <button type="submit" class="btn btn-primary mt-2">Guardar</button>
</form>

<?php require_once 'layouts/footer.phtml' ?>